name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-node@v4.0.0
        with:
          node-version-file: '.nvmrc'
      - name: Install
        run: yarn
      - name: Build
        run: yarn build
      # - name: Lint
      #   run: yarn lint
      - name: Type checking
        run: yarn typecheck
